const User = require('../models/User');
const Company = require('../models/Company');
const Investment = require('../models/Investment');
const logger = require('../config/logger');
const { runWorker } = require('../services/queueService');
const calculateMatchScore = require('../utils/matchmaker');

// Get All Investments (For an Investor)
exports.getMyInvestments = async (req, res) => {
    try {
        const investments = await Investment.find({ investor: req.user.id }).populate('company');
        res.json(investments);
    } catch (err) {
        logger.error(err.message, { metadata: { service: 'investController', method: 'getMyInvestments' } });
        res.status(500).send('Server Error');
    }
};

// Invest in a Company
exports.investInCompany = async (req, res) => {
    const { companyId, amount } = req.body;

    try {
        let company = await Company.findById(companyId);
        if (!company) return res.status(404).json({ msg: 'Company not found' });

        const investment = new Investment({
            investor: req.user.id,
            company: companyId,
            amount
        });

        await investment.save();

        // Update company raised amount
        company.amountRaised += amount;
        await company.save();

        // LOGGING: Critical financial transaction
        logger.info('Investment processed', {
            metadata: {
                type: 'FINANCIAL_TRANSACTION',
                investorId: req.user.id,
                companyId: companyId,
                amount: amount,
                timestamp: new Date()
            }
        });

        // WORKER QUEUE: Trigger Report Generation (Async)
        // This runs in the background and does not block the response
        runWorker('reportWorker.js', { userId: req.user.id, reportType: 'INVESTMENT_RECEIPT' })
            .then(result => logger.info('Report generated by worker', { metadata: result }))
            .catch(err => logger.error('Worker failed', { metadata: { error: err.message } }));

        res.json(investment);
    } catch (err) {
        logger.error(err.message);
        res.status(500).send('Server Error');
    }
};

// Update Investor Preferences
exports.updatePreferences = async (req, res) => {
    const { preferences } = req.body; // Expect array of strings
    try {
        const user = await User.findById(req.user.id);
        user.preferences = preferences;
        await user.save();
        res.json(user.preferences);
    } catch (err) {
        console.error(err.message);
        res.status(500).send('Server error');
    }
};

// Get AI Recommendations
exports.getRecommendations = async (req, res) => {
    try {
        const user = await User.findById(req.user.id);
        if (!user.preferences || user.preferences.length === 0) {
            return res.json([]);
        }

        const companies = await Company.find();

        const recommendations = companies.map(company => {
            const matchScore = calculateMatchScore(user.preferences, company);
            return {
                ...company._doc,
                matchScore
            };
        });

        // Sort by match score desc
        recommendations.sort((a, b) => b.matchScore - a.matchScore);

        // Return top 5
        res.json(recommendations.slice(0, 5));
    } catch (err) {
        console.error(err.message);
        res.status(500).send('Server error');
    }
};
